### ISSUE TITLE
Support Facebook Pages as party series links

### ISSUE THREAD

**Issue by glennlunder** [demozoo/demozoo#133]
Lots of parties these days have general Facebook pages that then play host to the events in question. There is currently no way to add these to a party series.

Example;

http://demozoo.org/parties/series/59/ (Arok party series)
https://www.facebook.com/ArokParty (Arok general facebook page)

**Comment by DannyCork** [comment]
another https://www.facebook.com/functiondemoparty/

**Comment by gasman** [comment]
Completed (by adding general external link support) in #582.
