### ISSUE TITLE
Progress feedback when uploading screenshots

### ISSUE THREAD

**Issue by tomaes** [demozoo/demozoo#135]
Some sort of progress feedback when uploading more than a couple of screenshots (or generally more than 2 MBytes worth of them) would be appreciated. I tend to upload bigger batches of screens and would like to know how many of them have already been processed. :)

**Comment by glennlunder** [comment]
I think we can close this ticket; it's a low-priority nice-to-have issue easily solved by functionality in the browser (Chrome) or via an addon (Firefox).
