### ISSUE TITLE
Support sixteencolors.net external links for ANSI art

### ISSUE THREAD

**Issue by glennlunder** [demozoo/demozoo#139]
What the topic says, really. :)

**Comment by glennlunder** [comment]
I'd like to clarify what I meant here;

What I'd like here is for links from the website sixteencolors.net to be recognized when they are added to ansi and ascii releases on Demozoo. The site does seem to experience some issues at the moment, as you can clearly see when clicking any of the top navigation links, so I am unable to provide examples just now.

I'm not sure what sort of activity this site has any longer either, with the popularity of textmod.es recently, so perhaps it's a good bet to leave this ticket for a little while and come back to it in a little bit, when hopefully they have solved their issues and we'll see.

**Comment by gasman** [comment]
Closing in favour of #436 which asks for the same thing but with a bit more detail.
