### ISSUE TITLE
Fix design of platform pages

### ISSUE THREAD

**Issue by glennlunder** [demozoo/demozoo#14]
Upon adding a new platform for Thomson - http://demozoo.org/platforms/53/ - I became keenly aware that there are some design issues with the current layout - most notably the fact that there is no border padding for the image, making text crush up against it.

It would also be preferable with the image right-aligned, so as to not break text formatting more than necessary.

**Comment by DannyCork** [comment]
Fixed but this issue is open :( Can someone close it please :)

**Comment by glennlunder** [comment]
Done.
