### ISSUE TITLE
Exclude videos from Productions Without Platforms

### ISSUE THREAD

**Issue by glennlunder** [demozoo/demozoo#153]
What it says in the title. We do not really need a platform for videos, so those could effectively be excluded from the list.

Suggested by Lotek on irc 204-06-12;

15:13 < ltk_tscc> I wonder if we should put "Video" also as a platform?
15:15 <@menacespb> We've already had this discussion, search the archives :) We decided that no, video is not a platform. It's a type.
15:19 <@menacespb> IMHO, it would not add significant value to have it as BOTH a type and a platform.
15:19 < ltk_tscc> well... the we should exclude all videos from the "prods without a platform-filter"
15:20 <@menacespb> Good point. We should. Making a ticket for that :)

**Comment by gasman** [comment]
You mean the 'productions without platforms' maintenance report? It does exclude video, and always has done: https://github.com/demozoo/demozoo/blob/master/maintenance/views.py#L122

(Please reopen if you can point to a specific example of a prod which is in the list but shouldn't be there!)
