### ISSUE TITLE
Tag Blacklist

### ISSUE THREAD

**Issue by sagamusix** [demozoo/demozoo#155]
People keep adding senseless tags, such as "demo", "intro", the group's name or some author's handle. I think having some kind of automatic blacklist for the most common mistakes could help. Blacklisting author and group names might be complicated, but disallowing e.g. "demo" to be used as a tag would already be a good start.

**Comment by glennlunder** [comment]
Suggestions for some blacklisted terms; 80286, 80386, 80486 (supplanted by 286, 386, 486).

Other obvious ones are related to common platforms, like amiga, ms-dos, windows, etc.

**Comment by sagamusix** [comment]
I guess in the case of the 80x86 tags, things get even more complicated (if we want to) since they should probably automatically be "redirected" to the corresponding x86 tags? Or, to make life simpler, every banned tag could have a description field, which in this case would say "Use the 386 tag instead".

**Comment by sagamusix** [comment]
Similar observations made recently: Some people used the "4channel" tag instead of "4ch". Automatic substitution for the most common cases still sounds like a good idea.

**Comment by gasman** [comment]
Implemented in #322
