### ISSUE TITLE
user bans (aka Baudsurfer / KOZMIK edit war)

### ISSUE THREAD

**Issue by tomaes** [demozoo/demozoo#157]
_Baudsurfer_, formerly known as _KOZMIK_ / _NEXTEMPIRE_ is constantly editing his own profile in an attempt to whitewash his scene release history. This has been going on for a while, and I think it looks like the only thing that would stop him is a permanent ban from the site. Which is unfortunate, but if we want to keep the db intact, a user ban feature must be considered. (big sites use "shadow bans" etc., but that seems a bit much, for a smaller project like DZ).

**Comment by glennlunder** [comment]
I agree. What sort of implementation would be most effective, in your eyes?

Ofcourse we could just disable his account, but that means there's nothing
to prevent him creating another account. Can we ban on ident, like on irc?

Alternatively, we could "lock" (and clearly signpost the fact) any profiles
and entries that have controversial edits.

-- Menace

**Comment by tomaes** [comment]
There could be a feature for locked credits, that normal users can't edit. For now, we can put the essential stuff in the info box, that he can't edit.

**Comment by gasman** [comment]
Page locking was implemented in #377. Admins have the ability to disable accounts, and for persistent offenders we can block account creation at the IP level (currently a hard-coded list, but we could potentially make this available to admins if the volume ever justifies it). For now this seems to be sufficient to keep bad behaviour under control.
