### ISSUE TITLE
Parties list by date is backwards

### ISSUE THREAD

**Issue by pulkomandy** [demozoo/demozoo#159]
http://demozoo.org/parties/by_date/ lists parties starting at 1984. The page is rather long, and people are usually interested in the most recent parties. So I think the page should list most recent parties first.

Possibly it should more clearly highlight currently happening and upcoming/future parties.

**Comment by glennlunder** [comment]
We have a new front page all but ready to be deployed that address those very issues - among other things, it has a nice tidy list of upcoming parties. :)

Though of course that doesn't invalidate your original issue - I agree that if nothing else, there should be a clickable newest/oldest switch on that page that address the sorting order issues.

**Comment by gasman** [comment]
The parties listing is now split by year and defaults to the current year, so I think this is covered now.

**Comment by pulkomandy** [comment]
Thanks, it's much better now!
