### ISSUE TITLE
Gzipped CSS/JS assets

### ISSUE THREAD

**Issue by sagamusix** [demozoo/demozoo#170]
Loading an essentially empty page, such as http://demozoo.org/parties/2690/, makes my browser download about 250kb of data. Doing a complete reload of the site download just about 277kb, so a large part of the resources are not cached. A huge chunk of this is JavaScript, since completely disabling JavaScript brings it down to about 50kb.
So it seems like resources like JS and CSS are not cached by the browser, and probably also not gzipped, resulting in more than 200kb of wasted bytes per page.

**Comment by sagamusix** [comment]
It seems that Firefox' wev developer tools count in the size of files with HTTP 304 responses into the total size, I'm not sure if I'm interpreting the output correctly. But even then, you may want to look at http://www.webpagetest.org/result/160523_QC_1825/ to check which files should still be gzipped and where to set the max-age/expires HTTP headers for static content.

**Comment by asbjornu** [comment]
Perhaps [CloudFlare])(https://www.cloudflare.com/)'s could be used to iron a few of these caching issues out? It's quite capable even in the free version.

**Comment by sagamusix** [comment]
As mentioned above, the caching issue was a non-issue. All the remains to be done is serving gzipped JS and CSS files.
In other news, this whole trend of moving all our traffic to be served by single company is completely disgusting.

**Comment by asbjornu** [comment]
> As mentioned above, the caching issue was a non-issue. All the remains to be done is serving gzipped JS and CSS files.

Yes, that's something CloudFlare could have done.

> In other news, this whole trend of moving all our traffic to be served by single company is completely disgusting.

I wouldn't use the word "disgusting", but I agree that the market dominance CloudFlare has is unfortunate.

**Comment by sagamusix** [comment]
Using CloudFlare would also be complete overkill - rather than just looking into the server config to update/enable the gzip/brotli configuration (at least gzip is trivial to do with most server software), you'd have to sign up with CloudFlare, change your DNS records, see what is broken now, etc... using their service would be in no proportion to the problem at hand.

**Comment by asbjornu** [comment]
Changing DNS records may be time easier spent than the development time required to fix this and #81 because it may be spent by someone else than the developer(s) working on the code. I'm not saying that's the case for Demozoo, it's just a general observation and CloudFlare has been a quick-fix that has proven useful to me in the past, that's all.

**Comment by nswaldman** [comment]
relevant to this discussion: https://github.com/demozoo/demozoo/issues/382

**Comment by gasman** [comment]
Implemented in f9c5cc4f363a3030bd75321f9ab7ff28440fff16 + c579297cdeadcafa3935a55a26f1afa082c85418.
