### ISSUE TITLE
use activity url link in profile drop down 

### ISSUE THREAD

**Issue by CanopyOverseer** [demozoo/demozoo#174]
a link when i'm logged in to show my previous activity edits/posts etc without having to drill to a place where i've done something to find the page (for me the target page would be http://demozoo.org/users/80/)

**Comment by DannyCork** [comment]
Visualisation of proposed change

![change](https://cloud.githubusercontent.com/assets/3512672/13666889/b9d53e2c-e6ab-11e5-861c-ef22e6b223a8.png)

**Comment by CanopyOverseer** [comment]
Looks good:)
