### ISSUE TITLE
Ability to add soundtrack links from the 'featured in' box on the music page

### ISSUE THREAD

**Issue by gasman** [demozoo/demozoo#18]
Kind of backwards from the way you'd normally do it, but can't hurt to add it as a feature: have an 'add production' link in the 'featured in...' box, allowing you to select a production to associate this bit of music with. (In this case, we wouldn't do anything meaningful with the 'ordering' field - if that was important, someone would have to go to the prod page and fix it.)

**Comment by glennlunder** [comment]
Following discussion on Slack, we've decided this does not need to remain an open ticket - which doesn't mean we won't implement it at some point.
