### ISSUE TITLE
More API endpoints

### ISSUE THREAD

**Issue by synbyte** [demozoo/demozoo#182]
Due to laziness, we'd like to consume the API to allow our group to update the productions on our website, without having to update our website.

Looking at the code, there doesn't seem to be an endpoint for grabbing a group and it's associated productions. Could this be made available?

Looking at the router, there does appear to be some adhoc endpoints to Pouet, but I can't find the correct URL to request to hit these.

**Comment by gasman** [comment]
Hi @synbyte - as it happens you're the second group to request this, and so there are a couple of (beta-status) endpoints that should hopefully do the job:
http://demozoo.org/api/v1/releasers/3009/productions/
http://demozoo.org/api/v1/releasers/3009/member_productions/

It's possible that the data format might get tweaked later (e.g. to add pagination) but I'll give you advance warning if that happens.

**Comment by synbyte** [comment]
Ah, that's exactly what I'm after. 

Thanks Matt, much appreciated. 

Any modification to the structure is understandable. Hopefully it doesn't stray too far from what it is currently, but if it does, do give me a nudge. I'm idling in the IRC channel. It's malodix, by the way. :)

I'd happily contribute some code, but I don't know enough about django, or python for that matter.

**Comment by synbyte** [comment]
Any chance of getting a sneaky request in to also have the screenshot URLs available?
