### ISSUE TITLE
Productions without screenshots maintenance report fails

### ISSUE THREAD

**Issue by glennlunder** [demozoo/demozoo#183]
Currently works for a good long while before throwing a "502 Bad Gateway" error.

Tested across multiple browsers (Chrome, Vivaldi) on Windows and Linux, just to weed out the chance of there being something client-specific that causes it to fail.

**Comment by gasman** [comment]
Fixed (and also filtered out prods with no downloads, to make the report not completely useless) in 4ee7212692cf7c92146b4d3e1754287f3456d4c5 + parents.
