### ISSUE TITLE
Maintenance report for broken download links from back2roots.org

### ISSUE THREAD

**Issue by glennlunder** [demozoo/demozoo#186]
The domain has lapsed, and downloads from files.back2roots.org (and possibly other subdomains) are no longer available.

**Comment by DannyCork** [comment]
The domain itself it now registered to a 3rd party. All links including any to subdomains no longer function.

Does DemoZoo have links to back2roots.org? If so all are now dead. Is it possible to automate the removal of all these defunkt links?

**Comment by glennlunder** [comment]
@DannyCork The way we've typically handled this scenario with a few other domains that went away, is we create a query on the backend (hence the term 'Maintenance report' for admins, where we can list any that pop up, and weed them out.

**Comment by DannyCork** [comment]
Thanks for clarifing this

**Comment by glennlunder** [comment]
I'm not even sure we have more of these in the database any longer, and I no longer see this domain cropping up so it's likely a non-issue at this point. Closing this.
