### ISSUE TITLE
demozoo local dev environment

### ISSUE THREAD

**Issue by DannyCork** [demozoo/demozoo#187]
I'd like to create a demoZoo dev environment locally. Is there a test database available that I can use? Even a sanitizied db or a db with just the basics ?

**Comment by gasman** [comment]
http://altaria.vm.bytemark.co.uk/seekrit/demozoo_export/ is a dump I created a while back with sensitive information stripped out (password hashes, non-public real names). Haven't tested it against the current codebase, but can hopefully be beaten into shape :-)

When I get chance, I'll set up a regular scheduled data dump like this, along with proper instructions for setting up a local dev instance.

**Comment by gasman** [comment]
Have now set up a regular redacted data export here:

http://data.demozoo.org/demozoo-export.sql.gz

A new dump is generated at 02:30 UTC every day. (or at least, it is if I've set it up correctly :-) )

**Comment by gasman** [comment]
Vagrant install script and setup instructions now added!

https://github.com/demozoo/demozoo/blob/master/README.md
