### ISSUE TITLE
points systems for submissions (glöps)

### ISSUE THREAD

**Issue by DannyCork** [demozoo/demozoo#190]
I'd like to propose a points system for contributors something similar to what exists on Pouet.

![screen shot 2016-03-14 at 21 08 13](https://cloud.githubusercontent.com/assets/3512672/13760016/e82eb7e6-ea28-11e5-92d2-8a846d1baeb7.png)

**Comment by glennlunder** [comment]
We discussed this at length in the design phase of Demozoo, and decided against it for two main reasons.

1) We do not want to just blindly copy other sites, we wanted to build our own site with our own community and our own "rewards", if you will.

2) While a point system for activity does drive some activity, it also leads to people adding shit just drive their score up - the socalled "glöpwhore" phenomenon.

**Comment by DannyCork** [comment]
glöpwhore :)
