### ISSUE TITLE
Change sumit button text

### ISSUE THREAD

**Issue by DannyCork** [demozoo/demozoo#199]
The screenshot submit button contains the text "submit Query"

![2016-04-14_1525](https://cloud.githubusercontent.com/assets/3512672/14531453/49553c22-0255-11e6-8d08-5c8148f01700.png)

This is techno babble. I'm not submitting a query, I'm submitting screenshots!

I propose the text is changed to "Submit" .It's to the point, simple and does what it says.

**Comment by DannyCork** [comment]
Upon futher inspection the current source contains 67 <input type="submit" instances.
The majority of these do not have value="" and hence the majority output "Submit Query".

I propose fixing all these. I hope this meets with your approval. If so I shall proceed.

**Comment by gasman** [comment]
Fixed in #202.
