### ISSUE TITLE
In membership lists, indicate sceners who have died

### ISSUE THREAD

**Issue by gasman** [demozoo/demozoo#20]
This has come up several times in discussions, and obviously needs to be handled sensitively. It was suggested that they could have a cross next to their name (although as a religious symbol this is contentious in itself...) or a 'flag' like AMP: http://www.amp.dascene.net/newresult.php?request=country&search=79 .

Further comments from Dipswitch:

> Now I know this is a controversial topic, and the old "list of deceased sceners" page at Scenewiki got shut down exactly because of that. It's obvious that it does not honor the memory of the deceased if the cause of their death (especially if being suicide or drug OD etc.) is up there on the internet. However, it is completely legitimate and, moreover, necessary for historical purposes to know and to note down whether and when a scener has died. We don't need to know any details, we just need to put down the fact and the date. It is, for example, important for dealing with double nicks (e.g. if we know that Superscen3r died in 2007, we for sure know that a "Superscen3r" who released a module in 2011 must be a different person).
> My suggestion is: We introduce a tick box "deceased" which is visible for admins only, thus preventing any abuse, accompanied by a field where one can enter a date (limited to year, exact date might be too much private information). The result could look like something I did for Crest manually in the notes: http://demozoo.org/sceners/36009/

**Comment by glennlunder** [comment]
It may be useful with a few examples for when/if we implement this;

http://demozoo.org/sceners/7363/
http://demozoo.org/sceners/44031/
http://demozoo.org/sceners/14158/
http://demozoo.org/sceners/4923/
http://demozoo.org/sceners/35476/
http://demozoo.org/sceners/8827/
http://demozoo.org/sceners/8853/
http://demozoo.org/sceners/6303/
http://demozoo.org/sceners/49773/
http://demozoo.org/sceners/40381/
http://demozoo.org/sceners/31767/
http://demozoo.org/sceners/30152/
http://demozoo.org/sceners/35397/
http://demozoo.org/sceners/1272/
http://demozoo.org/sceners/39142/
http://demozoo.org/sceners/31514/
http://demozoo.org/sceners/15360/
http://demozoo.org/sceners/1442/
http://demozoo.org/sceners/59201/
http://demozoo.org/sceners/78/
http://demozoo.org/sceners/29670/
http://demozoo.org/sceners/5045/
http://demozoo.org/sceners/49298/
http://demozoo.org/sceners/54450/

**Comment by glennlunder** [comment]
Following discussion on Slack, we do not see an added value to having this information hardcoded into a feature over mentions in the trivia field.
