### ISSUE TITLE
Maintenance report for music pieces without a Cowbell-compatible link

### ISSUE THREAD

**Issue by glennlunder** [demozoo/demozoo#205]
...So that once Cowbell lands, we can get a list of music pieces that require a compatible link (Modland, etc.) to become playable.

No reason why this couldn't be public-facing also, no harm in getting outsiders to add links.

**Comment by gasman** [comment]
Implemented in 6cbfbfab9d6a584d5756296f3382d326abb51edd:
https://demozoo.org/maintenance/tracked_music_without_playable_links
