### ISSUE TITLE
role "demozoo" does not exist

### ISSUE THREAD

**Issue by DannyCork** [demozoo/demozoo#206]
Am having an issue with demoZoo locally. It appears to be an error during the db import. What i did was :
```
git clone latest
cd demozoo
vagrant up
```

It appears that a post install script runs which has the following issue:

==> default:  54250K .......... .......... .......... .......... .......... 99% 10.8M 0s
==> default:  54300K .......... .......... .......... .......... .......... 99% 9.83M 0s
==> default:  54350K .......... .......... .......... .......... .......... 99% 10.9M 0s
==> default:  54400K .......... .......... .......... .......... .......... 99% 9.53M 0s
==> default:  54450K .......... .......... .......... .......... .......... 99% 10.7M 0s
==> default:  54500K .......... .......... .......... .......... .....     100% 7.62M=5.9s
==> default:
==> default: 2016-05-17 12:53:33 (9.10 MB/s) - ‘/home/vagrant/demozoo-export.sql.gz’ saved [55854327/55854327]
==> default:
==> default: ERROR:  role "demozoo" does not exist
==> default: ERROR:  role "demozoo" does not exist
==> default: ERROR:  role "demozoo" does not exist
==> default: ERROR:  role "demozoo" does not exist
==> default: ERROR:  role "demozoo" does not exist
==> default: ERROR:  role "demozoo" does not exist

**Comment by gasman** [comment]
I'm pretty sure those errors are harmless - you should be able to continue with the rest of the setup instructions. It probably wouldn't be too hard to fix them, though...

**Comment by jensadne** [comment]
That's postgres complaining about not being able to restore ownership because the role that owned things in the dumped database doesn't exist. The errors are indeed harmless, but also very easy to get rid of, just dump without ownership by adding the option -O when running pg_dump.

**Comment by gasman** [comment]
Fixed in f8d5c21e820eb5c65e774abc79be8a8b3c608ce7
