### ISSUE TITLE
Replacing entries in results tables (usability problem)

### ISSUE THREAD

**Issue by sagamusix** [demozoo/demozoo#22]
Let's say prod A is in some compo result table, but there's a dupe entry B that is much better (maybe because it has screenshots, credits and whatnot) but isn't linked to that compo. I'm not sure how this replacement is supposed to be done "properly" right now... Adding a new table row and deleting the old one? Sometimes you are able to still edit a table entry, but sometimes you can't modify it by clicking on it. If this was more consistent, it would probably make such replacement tasks simpler. On the other hand, I'm not sure how important this is if we are going to get a proper dupe merging functionality anyway.

**Comment by gasman** [comment]
I think this behaviour is a necessary evil - for data integrity reasons we need to clearly distinguish between the "replace a result row with a different prod" and "edit the details of an existing prod" cases.
