### ISSUE TITLE
Maintenance report for graphics with no screenshot, but with a download link

### ISSUE THREAD

**Issue by glennlunder** [demozoo/demozoo#224]
Should be pretty self-explanatory - I see a lot of stuff from graphics compos that has downloads but does not have a screenshot for whatever reason. Perhaps these were matched before we integrated RECOIL and this had support for them, hard to tell.

A maintenance report like this would make it easy to spot these and add screenshots to them.

Would also like the ability to exclude certain graphics for whatever reason - in some instances archives don't have files in a format we can read, or the archive itself is partially corrupt. No sense in those files appearing every time, so we should be able to weed them out to have a nice list of things to work on.

More screenshots = more attractive site :)

**Comment by glennlunder** [comment]
This is an excellent candidate for the publicly available maintenance reports, as well. Would love for this to be available soon :)

**Comment by gasman** [comment]
You can do this with the new version of the "prods without screenshots" report, via the filters at the top...

https://demozoo.org/maintenance/prods_without_screenshots?production_type=23

(This report only ever shows prods that have download links - that filter was added a while back to avoid having to wade through hundreds of 'lost' productions to find one that can actually be dealt with)
