### ISSUE TITLE
Rename downloads in accordance with changes on Modland

### ISSUE THREAD

**Issue by glennlunder** [demozoo/demozoo#228]
From an email from Coma;

"just a heads-up regarding a few changes on Modland. I made notes of them in readme_updates, so check there, but to summarize:

* Fasttracker, Octalyser and Soundtracker 2.6 are now back to their real suffix .mod instead of the inventions (by me) they had earlier. Already done.
* 15-sample Soundtracker modules will be moved out of Protracker to their own folder: Soundtracker. I'll take care of this during the next few days (weeks)."

For us, that means we must rename at least all downloads from modland with an .ft suffix to a .mod suffix, in order to make sure the downloads (and hence playback functionality) is still valid.

The other formats mentioned (Oktalyzer, SoundTracker 2.,6) are more esoteric, and there is likely only a handful of these in the database. The same goes for SoundTracker, I'll try to handle these manually.

**Comment by gasman** [comment]
Done. We had 25 *.ft links under /pub/modules/Fasttracker/ which I've fixed with a search-and-replace query, [one *.oct file](https://demozoo.org/music/55829/) which I've fixed manually, and no Soundtracker files.
