### ISSUE TITLE
Additional productions without platforms reports

### ISSUE THREAD

**Issue by glennlunder** [demozoo/demozoo#233]
Following on from discussions on Slack yesterday, I'd like to see the following two maintenance reports created;

- Productions Without Platforms EXCLUDING productions with the 'lost' tag set 
- Productions Without Platforms but WITH a download link

The reasoning should be pretty self-explanatory, but just for good measure - these would allow us to get to the "easy pickings" entries first, the ones where we can actually just investigate and figure out a platform, without the clutter of 2000 'lost' wild entries, where platform is anyone's guess as long as we have no matrial to look intro.

**Comment by gasman** [comment]
Implemented in c08aaa9c26c8121a365653032876ce9843916111 and 68f708ca1a98465eae9d481ad30976c6adf3a279
