### ISSUE TITLE
Login box: Input fields may overflow parent container

### ISSUE THREAD

**Issue by sagamusix** [demozoo/demozoo#236]
There seems to be no CSS to be associated with the input fields in the login box, so depending on the window manager, the box may look like this...

![login_box](https://cloud.githubusercontent.com/assets/875883/18102330/79c15c4c-6ef2-11e6-9000-06e745a91102.png)

Admittedly in this screenshot it doesn't look too bad, but on another machine the two input boxes actually overflowed into the site.

**Comment by nswaldman** [comment]
I've submitted a quick fix for that behaviour, because *yeesh*.
