### ISSUE TITLE
add gitHub integration to slack channel

### ISSUE THREAD

**Issue by DannyCork** [demozoo/demozoo#244]
I have this working locally and it's very nice.Configuration is literally 10 mins.
 This integration will post commits, pull requests, and activity on GitHub Issues to a channel in Slack.

- Create new Slack channel called Pull Requests or Github or something along these lines.
- add integration https://rootuid.slack.com/apps/A0F7YS2SX-github
- voila.

**Comment by gasman** [comment]
We have this already :-) (See #github-notifications on Slack)
