### ISSUE TITLE
New field for parties: "presented by <groupname>*"

### ISSUE THREAD

**Issue by cxw42** [demozoo/demozoo#251]
Related to #62 but not identical.  Some entries in the [Necta/scenemusic.net compo series](http://compos.scenemusic.net/) are represented as parties ([here](https://demozoo.org/parties/2251/), [here](https://demozoo.org/parties/1958/)).  However, there is nothing to indicate they are related.  If there were a field that each could be indicated as "Presented by [Nectarine](https://demozoo.org/groups/6280/) and [#cubernicus](https://demozoo.org/groups/18763/)," folks could at least navigate between them.  This would also apply to the Byterapers anniversary parties.

**Well,** I just now accidentally discovered the "Party series" function :) (e.g., [this](https://demozoo.org/parties/series/1144/)) ([fmb](https://demozoo.org/forums/post/1789/#post-1789)).  However, I think being able to list party hostgroups independently of series might still be useful, e.g., for parties with multiple hostgroups.

**Comment by glennlunder** [comment]
This is solved in https://github.com/demozoo/demozoo/pull/430
