### ISSUE TITLE
Layout issues on the forgotten password page

### ISSUE THREAD

**Issue by glennlunder** [demozoo/demozoo#252]
See image - pointed out by @Ziphoid, confirmed by myself on Windows 10, Chrome 53.0.2785.116 m (64-bit).

![image](https://cloud.githubusercontent.com/assets/2839057/18744222/490617be-80bd-11e6-8bd0-d779812a8bd6.png)

**Comment by gasman** [comment]
Assigning to @nswaldman as he was apparently [doing some reorganisation here](https://github.com/nswaldman/demozoo/commit/618d01dee6c5714e4bda55bc1eadcbeea8243a69#diff-5512b4bea08903a92df400c12e7a96de) before getting distracted :-)

**Comment by gasman** [comment]
Fix0red by @nswaldman in f991d94b5e03a6d30faba235278a69de0a6887de (and now deployed).
