### ISSUE TITLE
Author information way too small on search pages

### ISSUE THREAD

**Issue by sagamusix** [demozoo/demozoo#260]
Firefox on Windows 7, default zoom settings on a classic 96 DPI setup. Author information is almost unreadable.
![serp-font](https://cloud.githubusercontent.com/assets/875883/19951727/33898182-a160-11e6-9d0b-a194a75163ad.png)

I think it was also brought up that the forum font size could also be a tad bigger.

**Comment by nswaldman** [comment]
There's oodles of improvements related to the look of the search results, but I agree this should take precedent. I'll give it a band aid in terms of font-size, but the rest will leak in with the structural improvements.
