### ISSUE TITLE
add ability do add info to a download link

### ISSUE THREAD

**Issue by DannyCork** [demozoo/demozoo#277]
Take this prod https://demozoo.org/productions/166747/
It has 3 downloads, each download is valid.Each is a different portsof the same prod, one is for Amiga, 1 for Android etc...

To the user it appears that the download link is duplicated 3 times. 

![screen shot 2017-01-25 at 01 17 56](https://cloud.githubusercontent.com/assets/3512672/22274071/2d7bf270-e29c-11e6-84ba-8920b611daa3.png)

**Proposal**:
When entering a download url add the ability to enter some info.
store this info in the db
display this info.

**Comment by gasman** [comment]
Hi @DannyCork - this will be covered by #15.
