### ISSUE TITLE
Wrong party series ordering if two party editions have same date

### ISSUE THREAD

**Issue by sagamusix** [demozoo/demozoo#280]
Example: https://demozoo.org/parties/2155/

BCC1 and BCC2 happened in the same year, but the exact date is not available. Demozoo sorts them as "2 1 3 ..."

**Comment by gasman** [comment]
Note that the fix here is _not_ smart enough to order 10 after 9 (we only store the full party name, as a string, not the numeric value of the suffix). I'm kind of hoping that any party that reaches a 10th edition will be sufficiently well-documented that this doesn't happen ;-)
