### ISSUE TITLE
API: Production list items have no image thumbs

### ISSUE THREAD

**Issue by nswaldman** [demozoo/demozoo#287]
See description. It would be really nice if the production listing started to have just a single image available through the API.

**Comment by gasman** [comment]
Implemented in #602. You can now pass a `fields` URL parameter consisting of a comma-separated list of field names that includes `screenshots` to get the screenshots included as part of the listing - for example:

https://demozoo.org/api/v1/productions/?platform=2&production_type=1&has_screenshot=true&fields=id,url,demozoo_url,title,screenshots
