### ISSUE TITLE
.us scene.org mirror is back

### ISSUE THREAD

**Issue by glennlunder** [demozoo/demozoo#295]
After their flooding incident, all systems are go again - so the us mirror can be readded to the mirrors for scene.org downloads.

**Comment by glennlunder** [comment]
Dunno if our old configuration reflected this, but the us mirror actually mirrors the /mirrors/ subdirectory too, which some other scene.org mirrors do not. This means an extra mirror for every site under that umbrella, like ftp.amigascne.org and ftp.padua.org.

**Comment by gasman** [comment]
Fixed in ddaa08857d120ec6ac52739dcd740d2bfc0052e9 (and yep, we do recognise the mirrors of mirrors, and offer us.scene.org as one of the options for amigascne / padua links...)
