### ISSUE TITLE
Add REST API for getting demoparties

### ISSUE THREAD

**Issue by Bombe** [demozoo/demozoo#323]
Hi, I would like to request REST APIs for the following functions:

* Get a list of all demoparties, maybe filtered by year.
* Get information about a demoparty, e.g. the date.
* Get a list of all compos of a demoparty.
* Get a list of all entries of a compo.

**Comment by gasman** [comment]
First batch of info now up at http://demozoo.org/api/v1/party_series/ and http://demozoo.org/api/v1/parties/ , but no compo information yet.

**Comment by Bombe** [comment]
Nice. I’ll give that a first try tonight, hopefully. (There’s also “Justice League” on my schedule… :)

**Comment by Bombe** [comment]
Trying out the APIs right now…

**Comment by gasman** [comment]
Forgot to update here... :-)

I've since added compo data, as well as cross-references within the production API back to parties (for compo entries, out-of-compo releases and invitations), so hopefully this is feature-complete now.

**Comment by Bombe** [comment]
On first glance it looks okay. However, I have a problem reconstruction author information. Breakpoint 2010 (party 1), Exe 4k Gfx, #9. Website says: “Havocplague and Zoi / Inversion” but the JSON document doesn’t let me associate the author_affiliation_nicks with the correct author_nicks.

**Comment by gasman** [comment]
@Bombe Do you mean that there's no way to distinguish between "(Havocplague and Zoi) / (Inversion)" and "(Havocplague) and (Zoi / Inversion)"? That's a limitation of the Demozoo data model, not the API - please see #37.

**Comment by Bombe** [comment]
@gasman yes, that’s what I meant. Okay, if it’s not possible to get a clear distinction between those two I’ll simply trudge on (because I’m using this information only to create filenames).

**Comment by gasman** [comment]
Cool! Will close this for now, then (but happy to reopen or open a new issue if anything turns out to be missing).
