### ISSUE TITLE
Single white line between screenshots in mosaics on Firefox

### ISSUE THREAD

**Issue by glennlunder** [demozoo/demozoo#329]
It appears on Firefox 57.0.2 64-bit under Windows, the aforementioned anomaly appears on productions that have 4 or more screenshots - for example https://demozoo.org/productions/109217/

Illustration:
![image](https://user-images.githubusercontent.com/2839057/34070766-3ad70948-e26c-11e7-9aa8-31fc6823b950.png)

The issue does not present itself when the same production page is viewed on Chrome 63.0.3239.108 64-bit nor on Vivaldi 1.13 (1008.36) or the latest version of Microsoft Edge.

**Comment by sagamusix** [comment]
With Firefox 52 ESR on Windows 7, I don't see that extra line here. So either it's a new bug in later versions, or system-specific...

**Comment by sagamusix** [comment]
Hm, I can see the line when zooming into the site, so that gives me an idea: Are you using a high-DPI display, and is the display set to a different zoom level than 100% in Windows?

**Comment by glennlunder** [comment]
Yes, It's a 4K screen with scaling set to 125%.

**Comment by Bombe** [comment]
I can reproduce the white line on macOS Sierra on a 15” MBP (HiDPI) with Firefix 57.0.1 and 100% zoom. 
![image](https://user-images.githubusercontent.com/81599/34072107-9db1e154-e281-11e7-927a-98d6bdf1ab29.png)

**Comment by glennlunder** [comment]
I'm seeming more and more problems with this section, and I present another screenshot as "evidence", lifted from a render of https://demozoo.org/productions/181419/:

![image](https://user-images.githubusercontent.com/2839057/34154395-a7a1a9ca-e4b5-11e7-898e-c0fd437b47f7.png)

Here we see a _vertical_ white line, plus the screenshots are seemingly not aligning either... perhaps this is a sign of a bigger problem with the mosaic code?

**Comment by Bombe** [comment]
Also reproducible on macOS with Firefox (versions see above).

**Comment by sagamusix** [comment]
It's possibly not a problem on our side, but rather with Firefox' scaling. Even before high-DPI days, it was problematic in some situations.

**Comment by nswaldman** [comment]
You'll find that there are floating point pixel values for these thumbnail dimensions and yes, Firefox isn't great with that. There's several things wrong with the mosaic anyway it's a 4:3 tile that rarely aligns properly with non-4:3 screenshots (read: most screenshots), so it's probably a good idea to do something more than just fix a simple line artefact in one browser.

**Comment by gasman** [comment]
Fixed in #341
