### ISSUE TITLE
Maintenenace report for downloads from defunct sapphire.no site

### ISSUE THREAD

**Issue by glennlunder** [demozoo/demozoo#331]
A number of downloads have been listed from http://sapphire.no/~taxi/ascii/ and various subdirectories of that. AFAICT, the site has been gone for a good long while.

A maintenance report would be preferable to removing them outright, since it allows us to identify the entries with defunct links, and make sure we pop in replacement downloads. Almost everything from that site should be available on scene.org in /graphics/ascii these days, and if anything is missing, poke me and/or Dipswitch and we'll fix.

**Comment by gasman** [comment]
Here is the report, in all its glory...

https://demozoo.org/graphics/9312/

Yup, that's the only remaining prod with a sapphire.no link :-)

**Comment by glennlunder** [comment]
Hah, after I had deleted quite a few the last few days I figured it was a good idea to get a report to weed out the remaining ones. :D Guess I got most, then.
