### ISSUE TITLE
Maintenenace report for downloads from defunct thuglife.org site

### ISSUE THREAD

**Issue by glennlunder** [demozoo/demozoo#332]
http://www.thuglife.org used to be an ascii site, and there are a number of downloads from that url scattered around Demozoo. AFAICT, the site has been gone for a good long while.

A maintenance report would be preferable to removing them outright, since it allows us to identify the entries with defunct links, and make sure we pop in replacement downloads. Almost everything from that site should be available on scene.org in /graphics/ascii these days, and if anything is missing, poke me and/or Dipswitch and we'll fix.

**Comment by gasman** [comment]
Again there's just one prod in the database with a thuglife.org link: https://demozoo.org/productions/21609/
