### ISSUE TITLE
Add meta info to party pages

### ISSUE THREAD

**Issue by hervepiton** [demozoo/demozoo#336]
Right now there's no meta info on party pages so when sharing them on Facebook for instance, the preview shows no text or the first comment instead of more relevant information.

There's no image preview either, would it be possible to grab a random screenshot for a random release?

![image 1](https://user-images.githubusercontent.com/3500449/36199045-484a3b76-1170-11e8-84e5-75e91c8d0784.png)

**Comment by gasman** [comment]
Fixed in #339
