### ISSUE TITLE
Change csdb canonical links to csdb.dk

### ISSUE THREAD

**Issue by glennlunder** [demozoo/demozoo#337]
Today, we regex any csdb link and spit out a link like this: http://noname.c64.org/csdb/release/?id=162212

Hedning pointed out on our Slack that the preferred canonical link for the link above is this: http://csdb.dk/release/?id=162212

**Comment by Bombe** [comment]
I’d advocate not linking to csdb at all until they fix their goddamn SSL certificate which expired in twothousand fucking *twelve*.

**Comment by glennlunder** [comment]
That's not a productive attitude though. Asking them if we can help with the certificate, is. Several people in our crew have expertise in this field. Let's try and accomplish things together, rather than jumping directly to going "this sucks, screw it".

**Comment by sagamusix** [comment]
Just don't link to the HTTPS version then until they stop using their self-signed cert.
