### ISSUE TITLE
Too long party description makes results menu cover the description when scrolling down

### ISSUE THREAD

**Issue by jensadne** [demozoo/demozoo#342]
See for instance Revision 2018, https://demozoo.org/parties/3537/

To reproduce: expand the description text and scroll down, after a bit of scrolling the results menu will pop up and cover the description. See screenshots.

Before scrolling too far, everything fine:
http://media.qj.no/demozoo/party_description_bug1.png

A few lines further down and we get this:
http://media.qj.no/demozoo/party_description_bug2.png

Reproduced in both Chrome 64.0 and Firefox 54.0 here.

**Comment by glennlunder** [comment]
Can confirm in Chrome 65.0.3325.181 64-bit under Windows 10.

**Comment by nswaldman** [comment]
Fixed now!
