### ISSUE TITLE
Markdown bullet list support in news items

### ISSUE THREAD

**Issue by glennlunder** [demozoo/demozoo#345]
If memory serves, we support only a subset of Markdown in news items - so not the full feature list - and it would appear bullet lists are not a thing I can make happen. See my news item from today about Vice 3.2 for example.

According to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet I should be able to use - (minuses), + (pluses) or * (asterisks) but neither of those appear to work.

**Comment by gasman** [comment]
Probably just needs a CSS fix similar to fa1eb29e56cce6ba947f07e0a556cb2c9da10339. (We don't intentionally limit markdown features in news items - we're probably just missing the relevant styles.)

**Comment by nswaldman** [comment]
I would like to point out that this is why I consider wildcard style resets on lists the demonic saint of rework and underestimation.

**Comment by gasman** [comment]
I entirely agree and hate myself for being persuaded into thinking that they were a good idea once.

(Was there some valid reason for them in the semi-distant past, when IE and Firefox couldn't agree on what should be padding and what should be margin, or something? idk.)

**Comment by nswaldman** [comment]
(It seemed like a good idea at the time. That's what happens when the UI comes first and people never get to fight with the actual content -they forget that a conventional html page is a document first and that its UI concerns shouldn't overrule content concerns.)
