### ISSUE TITLE
Markdown ### in group pages (and probably other places) look funny

### ISSUE THREAD

**Issue by glennlunder** [demozoo/demozoo#346]
I did something I was probably not supposed to and used markdown ### to emphasize a heading for a new section in a group byline, and...

![image 3](https://user-images.githubusercontent.com/2839057/41232117-91f36e70-6d85-11e8-8689-92af2f7518b3.png)

That appeared slap bang in the middle of the text I was massaging.

@nswaldman asked me to make a ticket, so here we are.

**Comment by nswaldman** [comment]
Yeah, that's what panel titles look like -they've been styled as selectors, so any instance of a nicely semantic h3 inside, say, the notes panel will then look like a panel title. I wouldn't go as far as to go and call it a bug, but there you go :)

A band-aid has been submitted for testing. You should be able to write markdown on detail pages without glitches when this is approved.

**Comment by gasman** [comment]
Fixed in bb51525b1440175f79e22c487aae9babb9015967 / af9a0cf9585e382e58764c4fe43c2f2ea6345f20
