### ISSUE TITLE
Change scene.org download behaviour

### ISSUE THREAD

**Issue by glennlunder** [demozoo/demozoo#352]
Previously we've autopopulated download links for all the mirrors of scene.org when a link from any mirror has been added. This had the adverse sideeffect that most of the mirrors did not work until the files were synced to those mirrors, which was ofcourse janky when adding new download links from something that was just uploaded - for instance in the case of a party that had just released its files.

After some discussion on Slack following my opening of issue #349 , we've decided that it may be a better option to go with a single download link for scene.org productions going forward, as it seems the "Automatic" download link they provide now works very well.

**Comment by Gargaj** [comment]
Use the "resolve" endpoint: https://files.scene.org/api#resolve

**Comment by Gargaj** [comment]
Or this one I just added: https://files.scene.org/api/#info-mirrors

**Comment by glennlunder** [comment]
Even more pertinent now that new mirrors are added (Sweden) - I would like this ticket to be a priority. Not only would it make the interface less cluttered with a single scene.org download link, but it would also put less stress on the main scene.org servers if all downloads initiated from us are actually geo-distributed to the appropriate mirror automatically.

**Comment by gasman** [comment]
OK, how's this for a mockup?
<img width="1134" alt="screenshot 2019-01-28 at 19 30 51" src="https://user-images.githubusercontent.com/85097/51861113-4cc82480-2333-11e9-9e91-19f27377ea21.png">

Here, the main "Download (scene.org)" link would go to the direct download via the automatic mirror selector, and "file info" would go to the info page on scene.org.

**Comment by glennlunder** [comment]
Looks great, that's exactly what I was hoping for :)
