### ISSUE TITLE
Add feature to prevent editing a specific page by 'normal' users.

### ISSUE THREAD

**Issue by nswaldman** [demozoo/demozoo#360]
It appears to be necessary to add a feature where admins can prevent (or first authorise) changes made to specific pages. Some examples:

1. https://demozoo.org/productions/167829/ (dz entry for https://www.pouet.net/prod.php?which=68766 - user attempted to delete the complete reference, had to settle for defacing the page since only power users can delete actual pages)
2. https://demozoo.org/productions/182797/ (author consistently deletes any link other than his own dropbox link, treats the entry as his own personal page and tries to erase any reference of previous versions on demozoo)

Either locking down pages or having admins evaluate edits on 'sensitive' pages could be an option to avoid vandalism. Discuss!

**Comment by nswaldman** [comment]
This is somewhat related to ticket #326 by the way.

**Comment by gasman** [comment]
Implemented in #367
