### ISSUE TITLE
errors during vagrant up

### ISSUE THREAD

**Issue by DannyCork** [demozoo/demozoo#362]
I cloned the latest Demozoo
commit 31852ddf60673c8e13dbdb1a6c55da1c1c237435 (HEAD -> master, origin/master, origin/HEAD)
Author: Matt Westcott <matt@west.co.tt>
Date:   Thu Dec 20 19:06:50 2018 +0000

Then I ran
`vagrant up
`

After about 5 mins vargant errors, see below:

    default: ALTER TABLE
    default: ALTER TABLE
    default: REVOKE
    default: REVOKE
    default: GRANT
    default: GRANT
    default: /home/vagrant/.virtualenvs/demozoo/local/lib/python2.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
    default:   """)
    default: Operations to perform:
    default:   Apply all migrations: admin, auth, comments, contenttypes, demoscene, djcelery, forums, homepage, maintenance, mirror, pages, parties, platforms, pouet, productions, sceneorg, sessions, sites, taggit, zxdemo
    default: Running migrations:
    default:   No migrations to apply.
    default:   Your models have changes that are not yet reflected in a migration, and so won't be applied.
    default:   Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
    default: mkdir:
    default: cannot create directory ‘/home/vagrant/demozoo/static/svg’
    default: : No such file or directory
    default:
    default: > node-sass@4.9.3 install /home/vagrant/demozoo/node_modules/node-sass
    default: > node scripts/install.js
    default: Downloading binary from https://github.com/sass/node-sass/releases/download/v4.9.3/linux-x64-57_binding.node
    default: Download complete
    default: Binary saved to /home/vagrant/demozoo/node_modules/node-sass/vendor/linux-x64-57/binding.node
    default: Caching binary to /home/vagrant/.npm/node-sass/4.9.3/linux-x64-57_binding.node
    default:
    default: > node-sass@4.9.3 postinstall /home/vagrant/demozoo/node_modules/node-sass
    default: > node scripts/build.js
    default: Binary found at /home/vagrant/demozoo/node_modules/node-sass/vendor/linux-x64-57/binding.node
    default: Testing binary
    default: Binary is fine
    default: npm
    default:
    default: WARN
    default:
    default: optional
    default:  SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
    default: npm
    default:
    default: WARN
    default:
    default: notsup
    default:  SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
    default: added 759 packages from 298 contributors and audited 5529 packages in 53.868s
    default: found 0 vulnerabilities
    default:
    default: > demozoo@1.0.0 css /home/vagrant/demozoo
    default: > npm run sass && npm run autoprefixer && npm run cssnano
    default:
    default: > demozoo@1.0.0 sass /home/vagrant/demozoo
    default: > node-sass --importer node_modules/node-sass-glob-importer/dist/cli.js ./src/style/layout.scss ./static/css/dz.css
    default: Rendering Complete, saving .css file...
    default: Wrote CSS to /home/vagrant/demozoo/static/css/dz.css
    default:
    default: > demozoo@1.0.0 autoprefixer /home/vagrant/demozoo
    default: > postcss ./static/css/*.css --use autoprefixer --no-map -d ./static/css
    default:
    default: > demozoo@1.0.0 cssnano /home/vagrant/demozoo
    default: > postcss ./static/css/dz.css --no-map --use cssnano -o ./static/css/dz.css
    default:
    default: > demozoo@1.0.0 icons /home/vagrant/demozoo
    default: > npm run svgstore:icons && npm run svgo:icons
    default:
    default: > demozoo@1.0.0 svgstore:icons /home/vagrant/demozoo
    default: > svgstore -p icon-- -o ./static/svg/icons.svg ./src/svg/icons/*.svg
    default: fs.js:646
    default:   return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
    default:                  ^
    default:
    default: Error: ENOENT: no such file or directory, open './static/svg/icons.svg'
    default:     at Object.fs.openSync (fs.js:646:18)
    default:     at Object.fs.writeFileSync (fs.js:1299:33)
    default:     at Object.<anonymous> (/home/vagrant/demozoo/node_modules/svgstore-cli/bin/svgstore:48:8)
    default:     at Module._compile (module.js:653:30)
    default:     at Object.Module._extensions..js (module.js:664:10)
    default:     at Module.load (module.js:566:32)
    default:     at tryModuleLoad (module.js:506:12)
    default:     at Function.Module._load (module.js:498:3)
    default:     at Function.Module.runMain (module.js:694:10)
    default:     at startup (bootstrap_node.js:204:16)
    default: npm
    default:
    default: ERR!
    default:
    default: code
    default:  ELIFECYCLE
    default: npm
    default:
    default: ERR!
    default:
    default: errno
    default:  1
    default: npm
    default:
    default: ERR!
    default:  demozoo@1.0.0 svgstore:icons: `svgstore -p icon-- -o ./static/svg/icons.svg ./src/svg/icons/*.svg`
    default: npm
    default:
    default: ERR!
    default:  Exit status 1
    default: npm
    default:
    default: ERR!
    default:
    default: npm
    default:
    default: ERR!
    default:  Failed at the demozoo@1.0.0 svgstore:icons script.
    default: npm
    default:
    default: ERR!
    default:  This is probably not a problem with npm. There is likely additional logging output above.
    default: npm
    default:
    default: ERR!
    default:  A complete log of this run can be found in:
    default: npm
    default:
    default: ERR!
    default:      /home/vagrant/.npm/_logs/2018-12-22T02_05_46_617Z-debug.log
    default: npm
    default:
    default: ERR!
    default:
    default: code
    default:  ELIFECYCLE
    default: npm
    default:
    default: ERR!
    default:
    default: errno
    default:  1
    default: npm
    default:
    default: ERR!
    default:  demozoo@1.0.0 icons: `npm run svgstore:icons && npm run svgo:icons`
    default: npm
    default:
    default: ERR!
    default:  Exit status 1
    default: npm
    default:
    default: ERR!
    default:
    default: npm
    default:
    default: ERR!
    default:  Failed at the demozoo@1.0.0 icons script.
    default: npm
    default:
    default: ERR!
    default:  This is probably not a problem with npm. There is likely additional logging output above.
    default: npm
    default:
    default: ERR!
    default:  A complete log of this run can be found in:
    default: npm
    default:
    default: ERR!
    default:      /home/vagrant/.npm/_logs/2018-12-22T02_05_46_636Z-debug.log
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

Afterwards a 
`vagrant ssh`
works. 

Should I be concerned with the errors during variant up?

**Comment by nswaldman** [comment]
Going with the assumption that you're running a cleanly checkout out version, could you try this:

Shell into the vagrant box if you already didn't: 
``vagrant ssh``

Then ente rthe following:
``mkdir ./static/svg``

And run this bit last:
``npm run svgstore:icons``

Let me know if this runs without errors.

**Comment by nswaldman** [comment]
Never heard back on this one, but it's fixed in master now.

**Comment by DannyCork** [comment]
apologies for the delay
Your suggestion runs without any issues:

`(demozoo) vagrant@vagrant-ubuntu-trusty-64:~/demozoo$ mkdir ./static/svg
(demozoo) vagrant@vagrant-ubuntu-trusty-64:~/demozoo$ npm run svgstore:icons

> demozoo@1.0.0 svgstore:icons /home/vagrant/demozoo
> svgstore -p icon-- -o ./static/svg/icons.svg ./src/svg/icons/*.svg

(demozoo) vagrant@vagrant-ubuntu-trusty-64:~/demozoo$`
