### ISSUE TITLE
Remove Google+ social media integration

### ISSUE THREAD

**Issue by glennlunder** [demozoo/demozoo#370]
Now that Google is sunsetting Google+ pretty soon, and has communicated as much - it is pretty much a social media wasteland with huge barren landscapes of no users.

It's time to lose any code integrating it into our service, as well as dropping any links from the database. Not significant loss of information is assumed to happen because of this, but just to be safe I would not object to an export of said links so I can quickly browse through to make sure.

**Comment by nswaldman** [comment]
Wouldn't rush in to delete them from the database. There's no telling what might happen with the public data -who knows, archive.org might consider the footprint of Google+ meagre enough to keep a copy. See also Geocities :)

I mean, we're discussing the protection/privatisation of 20-year old email addresses in nfo files and being able to add old BBS phone numbers. Might as well hold on to it for now.

**Comment by gasman** [comment]
Since https://github.com/demozoo/demozoo/commit/71c95bd91bf60d3777d58d6c3e2ae284355cf955 we've had the ability to archive external links so that they don't show up on the frontend, but no data is deleted - I suggest we use that here.
