### ISSUE TITLE
Python 2.7 eol Jan 1st 2020

### ISSUE THREAD

**Issue by DannyCork** [demozoo/demozoo#372]
I did a pip install on the vagrant image and was informed 
`DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.`

Python 2.7 will be eol in 8 months time. Perhaps it's time to consider moving towards Python 3.x ?

**Comment by gasman** [comment]
It has been very much considered :-) In order to make the switch while being confident that we haven't broken anything, we'll have to considerably increase our test coverage - I made some progress on that a while back, but it's slow going.

**Comment by DannyCork** [comment]
Thanks for the reply @gasman , I didn't see an existing issue so I wanted to make sure it was raised.

What is the current state of affairs re unit tests, functional tests etc ?
I note there are api tests in demozoo/api/tests/ , a couple in demozoo/productions/tests/test_forms.py and any more I'm missing?

Perhaps I can assist with increasing the test coverage.

**Comment by gasman** [comment]
Now running successfully on Python 3.6.
