### ISSUE TITLE
Info files with long lines break site design

### ISSUE THREAD

**Issue by gasman** [demozoo/demozoo#373]
e.g. https://demozoo.org/productions/202719/info/1329/

**Comment by bengarrett** [comment]
Instead of using `<pre>` elements you could use `<p>` with the `white-space` CSS property. `pre-wrap` or `pre-line` values would fix this issue.

https://developer.mozilla.org/en-US/docs/Web/CSS/white-space

**Comment by glennlunder** [comment]
Here's an example of something that breaks quite horribly, since the text itself does not have nature cr's.

https://demozoo.org/productions/26286/info/10449/

Perhaps the best way to implement this would be some sort of toggle-able word wrap?
