### ISSUE TITLE
Chrome retirement of the ftp protocol in Q2 2020

### ISSUE THREAD

**Issue by bengarrett** [demozoo/demozoo#384]
Today it is reported that Chromium/Chrome 82 is to depreciate all support for the FTP protocol for both browsing and downloading. It has been expected for a few years, and one can assume Firefox will follow suit. 

Unfortunately this sunsetting will leave a significant number of download links on Demozoo and other sites broken, at least to web browsers. Though there is not much to do unless the FTP file hosts offer alternative HTTP support?

In the meantime, could it be prudent to start prioritising HTTP links over FTP links in the download links? Or make mention of the depreciation when people add new FTP links to the site?

[Intent to Deprecate: FTP Support](https://docs.google.com/document/d/1JUra5HnsbR_xmtQctkb2iVxRPuhPWhMB5M_zpbuGxTY/edit#heading=h.w330jny89ne2)
[Google Chrome 82 won't support FTP anymore](https://www.ghacks.net/2019/08/16/google-chrome-82-wont-support-ftp-anymore/)
[Chrome and Firefox Developers Aim to Remove Support for FTP](https://www.bleepingcomputer.com/news/google/chrome-and-firefox-developers-aim-to-remove-support-for-ftp/)

**Comment by gasman** [comment]
Untergrund is now serving over https as well as ftp: `ftp://ftp.untergrund.net/users/accountname/file.zip` => `https://ftp.untergrund.net/users/accountname/file.zip`

For scene.org, we're currently linking to the auto mirror select URL `https://files.scene.org/get/path/to/file.zip`, so we can sensibly leave it up to scene.org to update this to only serve http(s) sources as and when that becomes necessary (if indeed they're not already doing so).

**Comment by gasman** [comment]
Untergrund links now switched to https in 15d955c28a23ba03f7b5505e4df23991de193e42.

Out of 291274 download links in the database, there are now 63865 still using ftp, which can be broken down as:

* 37736 on Amigascne (which also serves http, and is mirrored by several scene.org mirrors with http support, so hopefully scene.org's auto mirror select should work for these too)
* 23811 on Modland (which also serves http from its primary server and several mirrors)
* 291 on padua.org (which seems to be ftp-only on its primary server, but is also mirrored by several scene.org mirrors with http support)
* 2027 others

**Comment by sagamusix** [comment]
ModLand would probably be an easy update of groklinks.py.

**Comment by gasman** [comment]
Done for amigascne and modland in #471 / #475 . I think we can call this done now, and deal with remaining sites on a case-by-case basis.
