### ISSUE TITLE
Add "no-screenshot" as an advanced search feature

### ISSUE THREAD

**Issue by glennlunder** [demozoo/demozoo#388]
In our advanced search options (see https://demozoo.org/search/?q=test+item&category= for an example of how it looks) it would be most useful to be able to add a tag for no-screenshot or similar, to search for something on a platform with no screenshots, for example.

**Comment by gasman** [comment]
Implemented as `screenshots:yes` / `screenshots:no`, e.g. https://demozoo.org/search/?q=platform%3Aatari+screenshots%3Ano
