### ISSUE TITLE
Mobile responsive design

### ISSUE THREAD

**Issue by glennlunder** [demozoo/demozoo#40]
We look terrible on mobile (phones and tablets), as "reported" by Ziphoid to me on irc today. In practice, the site is extremely hard to navigate on such screens since the design breaks so badly.

I was quite sure we had a trac ticket for this, but I can't find it.

**Comment by DannyCork** [comment]
3 years later I believe this ticket is no longer relevant. From my experience besides a couple of minor issues the site is very responsive :)

**Comment by glennlunder** [comment]
I agree. Some of our issues are certainly a bit stale at this point and/or have gotten fixed as a side effect of other development. I'm closing this issue and I say we rather open specific issues for specific non-responsive sections.
