### ISSUE TITLE
feature request: dark mode

### ISSUE THREAD

**Issue by Gapstare** [demozoo/demozoo#413]
I find mainly white websites to be taxing on the eyes. It'd be nice to be able to switch to a dark(er) background.

**Comment by glennlunder** [comment]
There are a lot of browser extensions that will fix that for you these days - this is just one random example I found for Chrome (and compatibles) from a quick search: https://chrome.google.com/webstore/detail/dark-mode/dmghijelimhndkbmpgbldicpogfkceaj

I suggest this gets fixed userside.
