### ISSUE TITLE
Add a 'nag' message when people try to add download links from known dead hosts

### ISSUE THREAD

**Issue by gasman** [demozoo/demozoo#42]
Apparently links to amigascne.org/old/ are still showing up in the database, despite Menace systematically fixing them a few months back - probably due to people blindly pasting in download links from Pouet. amiga.nvg.org is another dead host that we've now fixed all links from - in both cases, we have reports in http://demozoo.org/maintenance/ to tell us if they reappear.

We should add a bit of javascript to the 'edit download links' form to check the URL against 'known bad' hosts, and if it matches, display a warning message to the user telling them to check their links.

**Comment by DannyCork** [comment]
back2roots.org is another that has bitten the dust

**Comment by glennlunder** [comment]
This is simply not a huge problem any longer, and we have maintenance reports on the backend to weed out the few that do get added. Would rather have development muscle on more pressing matters.
