### ISSUE TITLE
Add support for defacto2 external links

### ISSUE THREAD

**Issue by glennlunder** [demozoo/demozoo#466]
defacto2 is a site with a long and stable track record, and it would be beneficial to have a favicon where links are added for sceners, groups and productions.

Site author @bengarrett provided a favicon for this use, attached.
[defacto2_floppydisk.zip](https://github.com/demozoo/demozoo/files/6403233/defacto2_floppydisk.zip)

**Comment by gasman** [comment]
Added in #471 / #475.
