### ISSUE TITLE
Streaming functionality for music

### ISSUE THREAD

**Issue by glennlunder** [demozoo/demozoo#49]
Roughly speaking, any place we'd have screenshots/thumbnails, music releases should have a player widget instead.

This will require mirroring tracks on S3 (because all major archives are FTP-based, which isn't supported consistently by browser audio facilities - and in any case, they're frequently packed inside zip files) and possibly re-encoding them too (as mp3 and ogg for cross-browser support - also, bandwidth considerations may mean that it's only feasible for us to offer low-bitrate versions, or <1 minute clips). For MODs and more exotic formats, we'll need to either render to mp3/ogg or look at client-side solutions (jsmodplayer is making good progress right now...)

**Comment by lotekstyle** [comment]
And to extend that... after speaking with the coder here... SNDH replay:

https://github.com/wothke/sc68-2.2.1

**Comment by glennlunder** [comment]
http://www.wothke.ch/blaster/ - click the what's this thing for a brief description of what this does. It may be useful to poke this guy about this.

Meanwhile, scene.org now offers in-browser replay of a number of streaming file formats like mp3 (audio) and mp4 (video).

**Comment by glennlunder** [comment]
http://www.a1k0n.net/2015/11/09/javascript-ft2-player.html

**Comment by glennlunder** [comment]
Gasman's comment from 24 Mar 2014 is no longer valid, since Digitale Kultur no longer hosts neither us nor a full scene.org mirror.

**Comment by gasman** [comment]
Implemented! Any enhancement requests for this feature should now be opened as a new ticket...
