### ISSUE TITLE
Feature Request: Show the number of releases attributed to that person

### ISSUE THREAD

**Issue by atarimark** [demozoo/demozoo#495]
On the page of a scener, could a count be added to show the number of releases attributed to that person?  
So on my page [here](https://demozoo.org/sceners/31808/) it would say MSD (347)?   (or whatever the number is, I guessed at 347).

I had a look around and could not see this information, if it is already there then please accept my ignorance and tell me where t click!

**Comment by gasman** [comment]
Implemented in #574
