### ISSUE TITLE
Set info files/board ads as NSFW content

### ISSUE THREAD

**Issue by m100bit** [demozoo/demozoo#506]
Everything in the title.
[Example](https://demozoo.org/bbs/2287/text_ad/4945/) if we really need this function (NSFW warning, yes).

**Comment by sagamusix** [comment]
This is essentially a duplicate of #36 (though at the time of creating that, BBS / NFO files didn't exist yet, so they should also be taken into account there)

**Comment by sagamusix** [comment]
@glennlunder I'd suggest to close this in favor of the already existing issue.

**Comment by glennlunder** [comment]
Agreed.
