### ISSUE TITLE
Assume a more suitable default encoding for info files depending on production platform

### ISSUE THREAD

**Issue by sagamusix** [demozoo/demozoo#508]
I think it would make sense that adding an info file for a prod should take the prod platform into account. For example, when adding an info file to an MS-DOS prod it should be safer to assume that it's in CP437 encoding rather than the current default, Windows-1252. For Amiga, ISO-8859-1 might be a sensible option.

**Comment by glennlunder** [comment]
This makes a whole lot of sense, and would eliminate a lot of manual clicking.

**Comment by gasman** [comment]
Have switched the default to CP437 in 1a3a5b9481d917e8e9425c83360c9195e7047c3b, as per #525. I think this is the best and simplest way to reduce bad guesses (since DOS prods are going to greatly outnumber any single ISO encoding), but can reconsider this if the error rate is still annoyingly high.
