### ISSUE TITLE
Differentiators are only shown for the primary name

### ISSUE THREAD

**Issue by sagamusix** [demozoo/demozoo#511]
Example: https://demozoo.org/groups/17457/

In this particular case, I set a differentiator for the second group name "Virus", because there are several Virus groups. However, the differentiator is not shown at all. It seems like they are only shown for the primary group name, but it would feel wrong to add it to that name because it's about differentiating the group's other name.

**Comment by ajoos** [comment]
That was fast! Thank you @gasman.
