### ISSUE TITLE
Demogroup emblems/insignias

### ISSUE THREAD

**Issue by Some1NamedNate** [demozoo/demozoo#531]
There should be a feature to attach a demogroup's emblem (e.g. the Farbrausch cart).

**Comment by glennlunder** [comment]
I see an immediate problem with that in that very, very few of the currently 25860 groups in the database have any sort of insignia.

If anything, I guess this dupes https://github.com/demozoo/demozoo/issues/30

**Comment by glennlunder** [comment]
No reply with further arguments for three days, so closing this.
