### ISSUE TITLE
Feature request: Tiktok link recognition

### ISSUE THREAD

**Issue by Paul-JanPauptit** [demozoo/demozoo#543]
While the demoscene is vastly underrepresented on tiktok, fact remains it is the most popular social platform in 2022.

I'm trying to give some demoparties a presence at this platform (flailing about like usual) but demozoo represents/stores links with the https://www.tiktok.com/@lovebyteparty pattern as a general WWW link.  Dedicated support would be nice.

**Comment by gasman** [comment]
It turns out we already added TikTok support in #488, but only for sceners/groups, not parties, and requiring a trailing slash on the URL. Fixed now!

**Comment by Paul-JanPauptit** [comment]
Perfection, those links look so very pretty now! Thank you for the fix.

 

Still no support on parties, right? (As the editing dialog only has website/twitter/pouet) . Not an issue, definitely not -this- issue, just want to double-check status. :-)

**Comment by Paul-JanPauptit** [comment]
You are absolutely right of course, thanks again!
