### ISSUE TITLE
Feature Request: list party urls on parties API

### ISSUE THREAD

**Issue by psenough** [demozoo/demozoo#556]
https://demozoo.org/api/v1/parties/

mostly interested in the API giving out a pouet id to help with interoperability with pouet API but i guess would be useful to expose all the listed websites

**Comment by gasman** [comment]
Implemented in #603 - as well as appearing on the detail view for an individual party, they can be added to the output of the listing view by passing a `fields` URL parameter that includes `external_links`, e.g. https://demozoo.org/api/v1/parties/?fields=url,id,name,external_links
