### ISSUE TITLE
More generic URLs to associate with demoparty series

### ISSUE THREAD

**Issue by sagamusix** [demozoo/demozoo#566]
With Twitter going down the drain, many parties use Mastodon as an alternative. However, on party series, you only can specify a Twitter profile ID which then shows up on all the individual party series entries. It would be great to extend this mechanism to cover other generic links as well, so that Mastodon profiles or other social media links don't have to be added to each entry individually.

**Comment by Paul-JanPauptit** [comment]
If it's any easier, "just add mastodon" (big handwaving) would be a very acceptable alternative as it is currently the de facto alternative to twitter for demoparties.

This message triggered by Deadline Demoparty officially moving to mastodon just after the party happened, so adding the account to the 2023 edition feels wrong, and adding it to the party itself is not possible. 😄
