### ISSUE TITLE
[Feature] Having external link to livecode.demozoo.org prettier

### ISSUE THREAD

**Issue by totetmatt** [demozoo/demozoo#567]
Would be nice to have dedicated icon and label like "Pouet" for livecode.demozoo.org external link
![image](https://github.com/demozoo/demozoo/assets/749891/32c0f3c7-af6f-4844-a487-1aca432c4947)

Example of current behaviour here : https://demozoo.org/parties/4652/

**Comment by gasman** [comment]
Now that we have proper LCDZ integration, with the cross-link shown (with dedicated icon/label) as part of the specific event within the party, I don't think it's necessary (or 'logically' correct in terms of the data structure) to have these as top-level links on the party.
