### ISSUE TITLE
Enable footnote support in markdown fields

### ISSUE THREAD

**Issue by nswaldman** [demozoo/demozoo#569]
"As a user, I want to be able to use footnotes in markdown content, so I can add useful information without breaking the flow of the main text."

While Markdown has link definitions that _kind of_ look like footnotes in the original markdown syntax, this formatting is lost when parsed to HTML like it is on Demozoo -so actual footnote formatting would be necessary. Markdown syntax [supports this](https://www.markdownguide.org/extended-syntax/#footnotes) and Python-Markdown has [an extension](https://python-markdown.github.io/extensions/footnotes/) for that.

**Comment by gasman** [comment]
Completed in #570
