### ISSUE TITLE
Problem with "cropped" Vimeo Link

### ISSUE THREAD

**Issue by RufUsul** [demozoo/demozoo#590]
can't add the right Vimeo Link https://vimeo.com/887527796/c9132ed6bc
to this https://demozoo.org/productions/202831/
always gets cropped to https://vimeo.com/887527796

**Comment by gasman** [comment]
It looks like this is Vimeo's format for an unlisted video - the hex code is effectively the 'pass code' for the video, and also needs special treatment in the URL to the embedded player (it becomes https://player.vimeo.com/video/887527796?h=c9132ed6bc).

We could handle this URL format as a special case with a 'split' parameter, similarly to how we store Youtube videos with a timestamp parameter as `K6gBkc9oqDI/2900s` (corresponding to https://www.youtube.com/watch?v=K6gBkc9oqDI&t=2900s) but this adds a bunch of fiddly regexp logic to the code, and I'm not sure if this situation is going to come up often enough to be worth it.

**Comment by RufUsul** [comment]
Hi gasman, for me it would be okay to put the working link in the "info box". Fits to "write-up" which is already there...

**Comment by gasman** [comment]
@RufUsul Added now! (It took me this long to realise it wasn't just another video of the demo...)

**Comment by RufUsul** [comment]
@gasman hehe, no problem ;-) -> for me it's perfect now!
