### ISSUE TITLE
[Bug] - Email is not getting triggered to Customer MailBox after resetting the password

### ISSUE THREAD

**Issue by dellstop123** [demozoo/demozoo#593]
**Steps to Reproduce:**

1. Open the website.
2. Click on Forget Password https://demozoo.org/account/forgotten_password/
3. Add your email. E.g: abc@gmail.com
4. Click on Reset Button

**Actual Result:**
  
 We are getting a password reset successful message in UI. But email is not triggered to Customer in their Mailbox.
![Screenshot 2024-02-10 at 11 35 46 PM](https://github.com/demozoo/demozoo/assets/23352270/b79e8e36-4bd1-4690-875c-eb949de24298)

**Expected Result:**

Email must be triggered to the customer in their mailbox.

**Comment by gasman** [comment]
Just tested, and it's working fine here - please check your spam filter.
