### ISSUE TITLE
New Paginator is showing "Previous page" pop-up on "Next page" button"

### ISSUE THREAD

**Issue by vitalkanev** [demozoo/demozoo#612]
To reproduce:
1. Go to a page that uses some kind of pagination, like [Recent Edits](https://demozoo.org/edits), [tag](https://demozoo.org/productions/tagged/first-production/) or [Productions index](https://demozoo.org/productions/?page=2)
2. Hover over the "&gt;&gt;" link at the bottom of the page
3. Notice it says "Previous page", *not* "Next page"

![](https://github.com/user-attachments/assets/990b1753-63c1-4294-bb27-b9c8755fe418)

**Comment by gasman** [comment]
Thanks @vitalkanev - good catch!
