### ISSUE TITLE
Allow searching for a specific content type (groups, sceners, parties etc)

### ISSUE THREAD

**Issue by glennlunder** [demozoo/demozoo#65]
Langford Huxley: I'm very much in favour of having a robust search experience in place upon launch. Being able to filter search results by type would be really, really helpful to users. The default search functionality spews out direct matches followed by likely ones. That's perfectly okay, but if you allow the user to filter the results on type with a couple of crude links, that alone would be brilliant for launch.

**Comment by lotekstyle** [comment]
Imho this is one of the more important tickets here... I get asked about that a lot :)

**Comment by mikrosk** [comment]
I agree, just today I've crossed this as well. I wanted to search for all atari productions with the *lost* tag and realised it's not possible. It would be totally awesome to have something like an universal, SQL-like queries possible. There's plenty of free libraries for that.

**Comment by glennlunder** [comment]
Recent discussion on our forum shows there is still demand for this to get resolved: https://demozoo.org/forums/post/2141/#post-2141

**Comment by nswaldman** [comment]
There's been some substantial work done by @gasman in the last few months, I'll be doing some layout improvements where applicable.

**Comment by gasman** [comment]
Completed in 6d5d4ac0b63b4bb5cd6e86248ac18fee3ae4194e

**Comment by mikrosk** [comment]
Has this really been resolved? What about lotek's use case:

> 11:21 < ltk_work> how do I find graphic X released 1997 in poland on system Y

or mine:

> I wanted to search for all atari productions with the lost tag

I could live even with manual entering URLs like this: https://demozoo.org/productions/tagged/68060/?platform=17&production_type= had this worked.

Adding more categories is a step forward but I felt the idea here is to make the search really flexible, not just adding a new combo box.

**Comment by gasman** [comment]
@mikrosk See the "advanced search help" dropdown on the search results page. There are some specific things mentioned above which it can't handle (for example, you can't generate a filtered listing without also providing a search term, and filtering for productions on "Atari" won't work because Atari spans multiple platforms) but those things will be better handled in separate tickets.

**Comment by mikrosk** [comment]
@gasman that 'atari' case was just a generalisation, I'd be totally fine to be able to search for 'Atari Falcon 030' + demo + specific tag(s). However I'm unable to find anything even remotely resembling the "advanced search help" dropbox:
![image](https://user-images.githubusercontent.com/3062260/42805477-3160c2ae-89ac-11e8-8f92-9b563998f00c.png)

**Comment by gasman** [comment]
@mikrosk You're looking at the productions listing view, not the search results. Enter something into the search box at the top of the page, and you'll arrive on the right page.

**Comment by mikrosk** [comment]
@gasman Ah, thank you. I don't use that search bar very often, usually I use demozoo for listing productions, not searching for them.

A few observations / suggestions:
- why isn't this "Advanced search help" link on the main page?
- why can't I search for empty/any production (i.e. just search for "tagged:68060" without providing any name)
- the help should include examples for multiple options, at least I hope "tagged:68060,ct60" or "year:2002-2004" is supposed to work like that?
- don't hide the help after search (or at least keep if when pushing the back button)
