### ISSUE TITLE
Youtube links for parties / party series

### ISSUE THREAD

**Issue by glennlunder** [demozoo/demozoo#73]
We do not have youtube support for demo parties. We need that, because  http://www.youtube.com/user/RevisionParty and such. It would actually be good to have both party series-wide (Revision, Assembly) and for specific editions (other parties I cannot remember right now, but I'm sure I've seen that!).

This would probably be the right time to implement the proper "paste in a full URL that gets matched with known URL types" mechanism on party series, which we don't have at the moment.

**Comment by gasman** [comment]
This has been supported for ages on individual parties, but generalised link recognition for party series is still on the todo list.

**Comment by glennlunder** [comment]
A user messaged me about this just now too - youtube.com/channelname links are not recognized, and I guess both groups and parties and such use those - it would be good to get these recognized finally.

**Comment by gasman** [comment]
Completed for party series in #582.
