### ISSUE TITLE
Middle-clicking on links should bypass lightbox handler, like ctrl+click does

### ISSUE THREAD

**Issue by glennlunder** [demozoo/demozoo#82]
reported by BoyC via Facebook: "Ok, usability feature #1 - a small thing really: when adding a prod to a group you get redirected to the finished prod page, which is fine of course, however if you're adding a lot of prods to a group you'll need to reopen the group page in edit mode for each release to do that. It'd be cool if the add new prod to group form could be opened in a new browser tab if needed.

Oh now I see that it can, but the behavior is a bit weird in Chrome at least: if you right click on the link and select "open in a new tab" it works nicely, but the default "open in new tab" middle click opens up the in page form."

"Thanks for the report - I'll get that fixed! I did include some logic to stop it activating the lightbox popup when ctrl+clicking, to allow for opening in a new tab - but I missed the possibility of middle-clicking, being a Mac user with only one mouse button ;-) - Gasman"

**Comment by nswaldman** [comment]
Middle click on a regular mouse now works as expected. Edge cases (left-handed mice, programmable devices) will very likely need more thought.
