### ISSUE TITLE
capped.tv old style links are not canonized properly

### ISSUE THREAD

**Issue by glennlunder** [demozoo/demozoo#95]
Saga: e.g.
 http://capped.tv/playeralt.php?vid=aenima-egon_and_dnci_first_man_on_mar
When trying to enter this link into the system, it breaks.

**Comment by DannyCork** [comment]
The capped.tv link is accepted by DemoZoo and displayed as a link however the url is shortened at the first full stop.

Instead of 
http://capped.tv/playeralt.php?vid=aenima-egon_and_dnci_first_man_on_mar

the link is 
http://capped.tv/playeralt

**Comment by glennlunder** [comment]
Not sure if we care as much about this any longer, as all the functionality that made capped.tv unique is now supported by the mainstream platforms, and it seems all but abandoned.
