### ISSUE TITLE
Indicate parties that were cancelled

### ISSUE THREAD

**Issue by glennlunder** [demozoo/demozoo#96]
I ran across the interesting case of Junction 1995 ( http://dev.demozoo.org/parties/2023/ ) this morning, a party that was planned, advertised, and then cancelled. It would be neat to be able to collect information on these events as well, but somehow clearly mark them as being cancelled - perhaps with a checkbox, in much the same way as a party can be marked 'online'.

**Comment by glennlunder** [comment]
PixelShow 2006 is another one, see comments here; http://demozoo.org/productions/8446/#comment-609

**Comment by glennlunder** [comment]
Milliways 2016 was cancelled - http://demozoo.org/parties/2810/

**Comment by glennlunder** [comment]
Random Access Overnight-Party II was cancelled - http://demozoo.org/parties/2887/

**Comment by glennlunder** [comment]
Saturne Party 2005 is another one that was cancelled. http://demozoo.org/parties/2964/

**Comment by glennlunder** [comment]
Aaaand another one, [Somewhere In Holland 1994](https://demozoo.org/parties/3052/).

**Comment by glennlunder** [comment]
[Demobit 1996](https://demozoo.org/productions/12885/) is another party that was invited to, then cancelled.

**Comment by glennlunder** [comment]
[Absolute 1999](https://demozoo.org/parties/3618/) was by all accounts cancelled.

**Comment by glennlunder** [comment]
[Durango 2004](http://web.archive.org/web/20040507001339/http://www.durangoparty.org/) was cancelled.

**Comment by sagamusix** [comment]
As it happens to be, there are a lot of cancelled parties this year, and in this case it's a bit more annoying because they also show up in the list of upcoming parties. So if this feature gets implemented eventually, the list of upcoming parties should also be taken into account.
